# Generated by Django 3.2.24 on 2024-04-27 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0003_complaint_created_at_complaint_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='bike_number',
            field=models.CharField(default='nothing', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint',
            name='uploaded_photo',
            field=models.FileField(default='Nothing', upload_to='complaint_photos/'),
            preserve_default=False,
        ),
    ]
