# Generated by Django 3.2.24 on 2024-04-27 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0004_auto_20240427_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='uploaded_photo',
            new_name='evidence_photo',
        ),
    ]
